name: Deploy to Kubernetes cluster

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - production
      - development
      - f/mvp2-460/auth0-migration

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install node dependencies
        run: npm ci
      - name: Install doctl (to be able to login on Digital Ocean)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Login to Digital Ocean docker registry
        run: doctl registry login
      - name: Build the docker image
        id: docker_build
        run: docker build . -q -t registry.digitalocean.com/wallfair/crash-game-k8s:${GITHUB_SHA::6}
      - name: Publish the docker image to Digital Ocean
        run: docker push registry.digitalocean.com/wallfair/crash-game-k8s:${GITHUB_SHA::6}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Edit deployment image (staging)
        if: github.ref == 'refs/heads/main'
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: 4.2.0
          command: |
            cd infra/environments/staging
            kustomize edit set image registry.digitalocean.com/wallfair/crash-game-k8s:${GITHUB_SHA::6}
            kustomize build .
      - name: Edit deployment image (development)
        if: github.ref == 'refs/heads/main'
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: 4.2.0
          command: |
            cd infra/environments/development
            kustomize edit set image registry.digitalocean.com/wallfair/crash-game-k8s:${GITHUB_SHA::6}
            kustomize build .
      - name: Edit deployment image (auth0)
        if: github.ref == 'refs/heads/f/mvp2-460/auth0-migration'
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: 4.2.0
          command: |
            cd infra/environments/auth0
            kustomize edit set image registry.digitalocean.com/wallfair/crash-game-k8s:${GITHUB_SHA::6}
            kustomize build .
      - name: Edit deployment image (production)
        if: github.ref == 'refs/heads/production'
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: 4.2.0
          command: |
            cd infra/environments/production
            kustomize edit set image registry.digitalocean.com/wallfair/crash-game-k8s:${GITHUB_SHA::6}
            kustomize build .
      - uses: actions-hub/kubectl@master
        if: github.ref == 'refs/heads/main'
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -k infra/environments/staging
      - uses: actions-hub/kubectl@master
        if: github.ref == 'refs/heads/development'
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -k infra/environments/development
      - uses: actions-hub/kubectl@master
        if: github.ref == 'refs/heads/f/mvp2-460/auth0-migration'
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -k infra/environments/auth0
      - uses: actions-hub/kubectl@master
        if: github.ref == 'refs/heads/production'
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -k infra/environments/production
  
